services:
  db:
    image: "postgres:alpine"
    restart: always
    env_file:
      - .env # Contains the POSTGRES_PASSWORD
    environment:
      - PGDATA=/var/lib/postgresql/data/lume
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
  redis:
    image: "redis:alpine"
    ports:
      - 6379:6379 