services:
  db:
    container_name: db
    image: "postgres:alpine"
    restart: always
    env_file:
      - .env # Contains the POSTGRES_PASSWORD
    environment:
      - PGDATA=/var/lib/postgresql/data/lume
    volumes:
      - ./data/db:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d
    ports:
      - 5432:5432
    networks:
      - lume
  api:
    container_name: api
    build: 
      context: ./api
    ports:
      - 80:80
    env_file:
      - .env
    environment:
      - JWT_ISSUER=lume-api
      - JWT_AUDIENCE=lume-clients
      - PORT=80
      - POSTGRES_HOST=db
    networks:
      - lume

networks:
  lume: